from colors import red as rosso
from colors import yellow as giallo
from colors import green as verde
from colors import cyan as ciano
from colors import blue as blu
from colors import purple as viola
from colors import pink as rosa
from colors import grey as grigio
from colors import black as nero
from colors import brown as marrone